# real-world example at https://github.com/Automattic/jetpack/blob/trunk/.github/files/required-review.yaml

- name: VaultPress & Backup
  paths:
   - 'projects/packages/**'
   - '!projects/plugins/*/composer.lock'
   - '!projects/plugins/*/composer.json'
   - '!projects/plugins/*/changelog/*'
  teams:
   - @matthewsullivan-instacart

# Jetpack Approvers review everything that hasn't been specifically assigned above.
# This needs to be last.
- name: Default to Jetpack Approvers
  paths: unmatched
  teams:
   - @sullivanmatt
