name: Security review
on: pull_request
  pull_request_review:
    types: [ submitted, edited, dismissed ]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  security_review:
    runs-on: ubuntu-latest

    # GitHub should provide a "pull_request_review_target", but they don't and
    # the action will fail if run on a forked PR.
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    timeout-minutes: 1
    steps:
      - uses: Automattic/action-required-review@8e71b7ea3407fe1da4ea3bd8d50bea2e787e66bc
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          requirements-file: .github/required-review.yaml
          status: Security review required
